# Generated by Django 4.2.7 on 2023-11-26 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_rename_deparment_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Departments',
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='DepartmentNAme',
            new_name='DepartmentName',
        ),
    ]
