# Generated by Django 4.2.7 on 2023-11-26 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_rename_department_departments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='Deparment',
            new_name='Department',
        ),
    ]
